server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home_school?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml
#  设置驼峰命名法
  configuration:
      map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.music.demo.mapper: debug
#    分页设置
mapper:
  mappers:
        - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


